# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app-03
#   namespace: platform
#   annotations: 
#     argocd-image-updater.argoproj.io/image-list: tuvx2000/pern-client
#     # argocd-image-updater.argoproj.io/write-back-method: git:secret:platform/git-creds
#     # argocd-image-updater.argoproj.io/git-branch: master
#   finalizers: 
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source: 
#     repoURL: https://github.com/tuvx2000/CICD-03.git
#     targetRevision: HEAD
#     path: Manifest-Files/my-app-to-exec-cp-01
#   destination:
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
    
    