apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-service-efs
  # No namespace, PVs are global
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
  claimRef:
    name: my-service-efs
    namespace: my-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-service-efs
  namespace: my-service
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi