apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: tuvx2000/pern-server:v0.4
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
    
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pern-backend-deployment
#   labels:
#     app: pern-server
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pern-server
#   template:
#     metadata:
#       labels:
#         app: pern-server
#     spec:
#       containers:
#       - name: pern-server
#         image: tuvx2000/pern-server:v0.2
#         ports:
#         - containerPort: 5001
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pern-server-service
# spec:
#   selector:
#     app.kubernetes.io/name: pern-server
#   ports:
#   - name: tcp
#     protocol: TCP
#     port: 5001
#     targetPort: 5001
