apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    run: angular-webapp
spec:
  ports: 
  - protocol: TCP
    port: 3080
    targetPort: 3080
  selector:
    app: angular-webapp
  # type: NodePort