--- 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test03
replicas: 
  - name: nginx-03
    count: 1
images: 
  - name: tuvx2000/pern-client
    newTag: v0.9
resources: 
  - ../my-app-base-cp-01
