---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-01
  # namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:  
      containers:
      - name: nginx
        image: tuvx2000/cicd-gitlab:v0.1.0
        ports:
          - containerPort: 80
      # imagePullSecrets: -> created in kustomization
      #   - name: dockerconfigjson 

  